# Generated by Django 3.1 on 2020-09-18 13:43

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mechanic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('contact_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bot_app.contact')),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bot_app.address')),
            ],
            bases=('bot_app.contact',),
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_initiated', models.DateTimeField(auto_now_add=True)),
                ('date_scheduled', models.DateTimeField()),
                ('status', models.CharField(choices=[('FI', 'Finished'), ('ST', 'Started'), ('RE', 'Needs rescheduling'), ('WI', 'Wrong address')], default='ST', max_length=2)),
                ('comments', models.TextField()),
                ('mechanic', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot_app.mechanic')),
                ('customer', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot_app.customer')),
            ],
        ),
    ]
