# Generated by Django 3.1 on 2020-10-02 01:24

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('phone_number', models.CharField(help_text='Número de telefone', max_length=15, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('address', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Mechanic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nome do mecânico', max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_initiated', models.DateTimeField(auto_now_add=True)),
                ('date_scheduled', models.DateTimeField(help_text='Data da realização do serviço')),
                ('status', models.CharField(choices=[('FI', 'Finished'), ('ST', 'Started'), ('RE', 'Needs rescheduling'), ('WI', 'Wrong address')], default='ST', max_length=2)),
                ('comments', models.TextField(blank=True, help_text='Observações sobre o serviço')),
                ('customer', models.ForeignKey(help_text='Cliente', null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot_app.customer')),
                ('mechanic', models.ForeignKey(help_text='Mecânico responsável', null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot_app.mechanic')),
            ],
        ),
    ]
