# Generated by Django 3.1 on 2020-11-16 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='address',
            field=models.CharField(help_text='Endereço onde será realizado o serviço. Ex: Rua das Rosas, 210', max_length=200, verbose_name='Endereço do serviço'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='city',
            field=models.CharField(help_text='Cidade', max_length=50),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='state',
            field=models.CharField(choices=[('SP', 'São Paulo'), ('RJ', 'Rio de Janeiro'), ('MG', 'Minas Gerais'), ('RS', 'Rio Grande do Sul'), ('PR', 'Paraná'), ('SC', 'Santa Catarina'), ('BA', 'Bahia'), ('DF', 'Distrito Federal'), ('GO', 'Goiás'), ('PE', 'Pernambuco'), ('PA', 'Pará'), ('CE', 'Ceará'), ('MT', 'Mato Grosso'), ('ES', 'Espírito Santo'), ('MS', 'Mato Grosso do Sul'), ('AM', 'Amazonas'), ('MA', 'Maranhão'), ('RN', 'Rio Grande do Norte'), ('PB', 'Paraíba'), ('AL', 'Alagoas'), ('PI', 'Piauí'), ('RO', 'Rondônia'), ('SE', 'Sergipe'), ('TO', 'Tocantins'), ('AP', 'Amapá'), ('AC', 'Acre'), ('RR', 'Roraima')], help_text='Estado', max_length=2),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='zip_code',
            field=models.CharField(help_text='CEP, sem traço', max_length=10),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(help_text='Nome e sobrenome', max_length=150, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(help_text='Número de telefone celular com DDD, somente números. Ex: 11987654321', max_length=15, unique=True, verbose_name='Número telefone'),
        ),
        migrations.AlterField(
            model_name='mechanic',
            name='account_number',
            field=models.CharField(blank=True, help_text='Número da conta, com traços', max_length=15, verbose_name='Número da conta'),
        ),
        migrations.AlterField(
            model_name='mechanic',
            name='account_owner_name',
            field=models.CharField(blank=True, help_text='Nome completo do proprietário da conta', max_length=100, verbose_name='Proprietário da conta'),
        ),
        migrations.AlterField(
            model_name='mechanic',
            name='address',
            field=models.CharField(blank=True, help_text='Endereço, com número. Ex: Rua das Rosas, 210', max_length=200, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='mechanic',
            name='bank',
            field=models.CharField(blank=True, help_text='Nome do banco', max_length=50, verbose_name='Banco'),
        ),
        migrations.AlterField(
            model_name='mechanic',
            name='branch',
            field=models.CharField(blank=True, help_text='Agência', max_length=10, verbose_name='Agência'),
        ),
        migrations.AlterField(
            model_name='mechanic',
            name='city',
            field=models.CharField(blank=True, help_text='Cidade. Ex: São Paulo', max_length=50, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='mechanic',
            name='complement',
            field=models.CharField(blank=True, help_text='Complemento do endereço, se houver', max_length=200, verbose_name='Complemento'),
        ),
        migrations.AlterField(
            model_name='mechanic',
            name='cpf',
            field=models.CharField(blank=True, help_text='CPF, com pontos e traços', max_length=11, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='mechanic',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='mechanic',
            name='name',
            field=models.CharField(help_text='Nome e sobrenome', max_length=150, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='mechanic',
            name='owner_id',
            field=models.CharField(blank=True, help_text='CPF ou CNPJ do proprietário da conta', max_length=20, verbose_name='Documento do proprietário'),
        ),
        migrations.AlterField(
            model_name='mechanic',
            name='phone_number',
            field=models.CharField(help_text='Número de telefone celular com DDD, somente números. Ex: 11987654321', max_length=15, unique=True, verbose_name='Número telefone'),
        ),
        migrations.AlterField(
            model_name='mechanic',
            name='rg',
            field=models.CharField(blank=True, help_text='RG, com pontos e traços', max_length=14, verbose_name='RG'),
        ),
        migrations.AlterField(
            model_name='mechanic',
            name='state',
            field=models.CharField(blank=True, choices=[('SP', 'São Paulo'), ('RJ', 'Rio de Janeiro'), ('MG', 'Minas Gerais'), ('RS', 'Rio Grande do Sul'), ('PR', 'Paraná'), ('SC', 'Santa Catarina'), ('BA', 'Bahia'), ('DF', 'Distrito Federal'), ('GO', 'Goiás'), ('PE', 'Pernambuco'), ('PA', 'Pará'), ('CE', 'Ceará'), ('MT', 'Mato Grosso'), ('ES', 'Espírito Santo'), ('MS', 'Mato Grosso do Sul'), ('AM', 'Amazonas'), ('MA', 'Maranhão'), ('RN', 'Rio Grande do Norte'), ('PB', 'Paraíba'), ('AL', 'Alagoas'), ('PI', 'Piauí'), ('RO', 'Rondônia'), ('SE', 'Sergipe'), ('TO', 'Tocantins'), ('AP', 'Amapá'), ('AC', 'Acre'), ('RR', 'Roraima')], max_length=2, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='mechanic',
            name='zip_code',
            field=models.CharField(blank=True, help_text='CEP, com traços', max_length=10, verbose_name='CEP'),
        ),
    ]
