# Generated by Django 3.1 on 2020-10-05 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mechanic',
            old_name='name',
            new_name='name_mechanic',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('FI', 'Finalizado'), ('ST', 'Iniciado'), ('RE', 'Reagendar'), ('WI', 'Endereço incorreto')], default='ST', max_length=2),
        ),
    ]
