# Generated by Django 3.1 on 2020-10-05 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0002_auto_20201005_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='type',
            field=models.CharField(choices=[('NB', 'Montagem Bike Nova'), ('EB', 'Montagem Bike Ergométrica'), ('ET', 'Revisão Expert'), ('SS', 'Serviço Expert'), ('FN', 'Pneu Furado Bike Não Elétrica'), ('FE', 'Pneu Furado Bike Elétrica')], default='SS', help_text='Tipo de serviço', max_length=2),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('FI', 'Finalizado'), ('ST', 'Iniciado'), ('RE', 'Reagendar'), ('WI', 'Endereço incorreto')], default='ST', help_text='Status do serviço', max_length=2),
        ),
    ]
