# Generated by Django 3.1 on 2020-10-05 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0003_auto_20201005_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='type',
            field=models.CharField(choices=[('NB', 'Montagem Bike Nova'), ('EB', 'Montagem Bike Ergométrica'), ('ET', 'Revisão Expert'), ('SS', 'Serviço Select'), ('FN', 'Pneu Furado Bike Não Elétrica'), ('FE', 'Pneu Furado Bike Elétrica')], default='SS', help_text='Tipo de serviço', max_length=2),
        ),
    ]
