# Generated by Django 3.1 on 2020-10-07 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0004_auto_20201005_2053'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(help_text='Mensagem do cliente')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(help_text='Mensagem enviada por', on_delete=django.db.models.deletion.CASCADE, to='bot_app.customer')),
            ],
        ),
    ]
